<a href="https://colab.research.google.com/github/prkalva10/Collab/blob/main/Testes_com_dados_Mega_Sena.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.1.4)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
print("Olá mundão")

Olá mundão

In [ ]:
df = pd.read_csv("/content/sorteios.csv")

In [ ]:
df.head()

,Id,Concurso,Data Sorteio,1ª Dezena,2ª Dezena,3ª Dezena,4ª Dezena,5ª Dezena,6ª Dezena,Arrecadacao_Total,...,Rateio_Sena,Ganhadores_Quina,Rateio_Quina,Ganhadores_Quadra,Rateio_Quadra,Acumulado,Valor_Acumulado,Estimativa_Prêmio,Acumulado_Mega_da_Virada,Unnamed: 22
0,1,1,11/03/1996,41,5,4,52,30,33,"0,00",...,"0,00",17,"39.158,92",2016,"330,21",SIM,"1.714.650,23","0,00","0,00",NaN
1,2,2,18/03/1996,9,39,37,49,43,41,"0,00",...,"2.307.162,23",65,"14.424,02",4488,"208,91",NÃO,"0,00","0,00","0,00",NaN
2,3,3,25/03/1996,36,30,10,11,29,47,"0,00",...,"391.192,51",62,"10.515,93",4261,"153,01",NÃO,"0,00","0,00","0,00",NaN
3,4,3,25/03/1996,36,30,10,11,29,47,"0,00",...,"391.192,51",62,"10.515,93",4261,"153,01",NÃO,"0,00","0,00","0,00",NaN
4,5,4,01/04/1996,6,59,42,27,1,5,"0,00",...,"0,00",39,"15.322,24",3311,"180,48",SIM,"717.080,75","0,00","0,00",NaN

In [ ]:
nomes = df["Data Sorteio"]
nomes

0       11/03/1996
1       18/03/1996
2       25/03/1996
3       25/03/1996
4       01/04/1996
           ...
2273    11/07/2018
2274    14/07/2018
2275    18/07/2018
2276    21/07/2018
2277    25/07/2018
Name: Data Sorteio, Length: 2278, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2278 entries, 0 to 2277
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        2278 non-null   int64
 1   Concurso                  2278 non-null   int64
 2   Data Sorteio              2278 non-null   object
 3   1ª Dezena                 2278 non-null   int64
 4   2ª Dezena                 2278 non-null   int64
 5   3ª Dezena                 2278 non-null   int64
 6   4ª Dezena                 2278 non-null   int64
 7   5ª Dezena                 2278 non-null   int64
 8   6ª Dezena                 2278 non-null   int64
 9   Arrecadacao_Total         2278 non-null   object
 10  Ganhadores_Sena           2278 non-null   int64
 11  Cidade                    392 non-null    object
 12  UF                        678 non-null    object
 13  Rateio_Sena               2278 non-null   object
 14  Ganhadores_Quina          2278 non-null   int64
 15  Rateio_Quina              2278 non-null   object
 16  Ganhadores_Quadra         2278 non-null   int64
 17  Rateio_Quadra             2278 non-null   object
 18  Acumulado                 2278 non-null   object
 19  Valor_Acumulado           2278 non-null   object
 20  Estimativa_Prêmio         2278 non-null   object
 21  Acumulado_Mega_da_Virada  2278 non-null   object
 22  Unnamed: 22               0 non-null      float64
dtypes: float64(1), int64(11), object(11)
memory usage: 409.5+ KB

In [ ]:
df.describe()

,Id,Concurso,1ª Dezena,2ª Dezena,3ª Dezena,4ª Dezena,5ª Dezena,6ª Dezena,Ganhadores_Sena,Ganhadores_Quina,Ganhadores_Quadra,Unnamed: 22
count,2278.000000,2278.000000,2278.000000,2278.000000,2278.000000,2278.000000,2278.000000,2278.000000,2278.000000,2278.000000,2278.000000,0.0
mean,1139.500000,1046.037752,30.441176,29.809482,30.546971,30.689640,30.054434,29.757682,0.774802,172.262511,9964.825724,NaN
std,657.746278,595.929308,17.439520,17.360566,17.518250,17.225998,17.236672,17.404741,2.127623,461.009424,19591.148738,NaN
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,6.000000,683.000000,NaN
25%,570.250000,529.000000,15.000000,15.000000,15.000000,16.000000,15.000000,15.000000,0.000000,52.000000,3994.250000,NaN
50%,1139.500000,1056.500000,31.000000,30.000000,30.000000,31.000000,30.500000,30.000000,0.000000,83.000000,5764.500000,NaN
75%,1708.750000,1560.000000,46.000000,45.000000,46.000000,45.000000,45.000000,45.000000,1.000000,136.750000,8816.250000,NaN
max,2278.000000,2062.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,17.000000,4862.000000,173428.000000,NaN

In [ ]:
precos = [100,250,89,430,175]

In [ ]:
print(precos)

[100, 250, 89, 430, 175]

In [ ]:
precos_com_iva = []

In [ ]:
precos_com_iva = [p * 1.10 for p in precos]

In [ ]:
precos_com_iva

[110.00000000000001, 275.0, 97.9, 473.00000000000006, 192.50000000000003]

In [ ]:
precos_com_iva = [p for p in precos if p > 150]

In [ ]:
precos_com_iva

[250, 430, 175]

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("olistbr/brazilian-ecommerce")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'brazilian-ecommerce' dataset.
Path to dataset files: /kaggle/input/brazilian-ecommerce

In [ ]:
print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/brazilian-ecommerce

In [ ]:
df_orders_items = pd.read_csv(path + "/olist_order_items_dataset.csv")
df_orders_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [ ]:
df_products = pd.read_csv(path + "/olist_products_dataset.csv")
df_products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [ ]:
df_categories = pd.read_csv(path + "/product_category_name_translation.csv")
df_categories.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [ ]:
df_categories.tail()

            product_category_name product_category_name_english
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

In [ ]:
import pandas as pd

In [ ]:
df_orders_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [ ]:
vendas_vendedores = df_orders_items.groupby("seller_id")["price"].sum()

In [ ]:
vendas_vendedores

seller_id
0015a82c2db000af6aaaf3ae2ecb0532     2685.00
001cca7ae9ae17fb1caed9dfb1094831    25080.03
001e6ad469a905060d959994f1b41e4f      250.00
002100f778ceb8431b7a1020ff7ab48f     1234.50
003554e2dce176b5555353e4f3555ac8      120.00
                                      ...
ffcfefa19b08742c5d315f2791395ee5       69.90
ffdd9f82b9a447f6f8d4b91554cc7dd3     2101.20
ffeee66ac5d5a62fe688b9d26f83f534     1839.86
fffd5413c0700ac820c7069d66d98c89     9062.30
ffff564a4f9085cd26170f4732393726     1426.30
Name: price, Length: 3095, dtype: float64

In [ ]:
rankings_vendedores = vendas_vendedores.sort_values(ascending=False)

In [ ]:
rankings_vendedores

seller_id
4869f7a5dfa277a7dca6462dcf3b52b2    229472.63
53243585a1d6dc2643021fd1853d8905    222776.05
4a3ca9315b744ce9f8e9374361493884    200472.92
fa1c13f2614d7b5c4749cbc52fecda94    194042.03
7c67e1448b00f6e969d365cea6b010ab    187923.89
                                      ...
34aefe746cd81b7f3b23253ea28bef39         8.00
702835e4b785b67a084280efca355756         7.60
1fa2d3def6adfa70e58c276bb64fe5bb         6.90
77128dec4bec4878c37ab7d6169d6f26         6.50
cf6f6bc4df3999b9c6440f124fb2f687         3.50
Name: price, Length: 3095, dtype: float64

In [ ]:
rankings_vendedores.head(10)

seller_id
4869f7a5dfa277a7dca6462dcf3b52b2    229472.63
53243585a1d6dc2643021fd1853d8905    222776.05
4a3ca9315b744ce9f8e9374361493884    200472.92
fa1c13f2614d7b5c4749cbc52fecda94    194042.03
7c67e1448b00f6e969d365cea6b010ab    187923.89
7e93a43ef30c4f03f38b393420bc753a    176431.87
da8622b14eb17ae2831f4ac5b9dab84a    160236.57
7a67c85e85bb2ce8582c35f2203ad736    141745.53
1025f0e2d44d7041d6cf58b6550e0bfa    138968.55
955fee9216a65b617aa5c0531780ce60    135171.70
Name: price, dtype: float64

In [ ]:
pip install nbstripout

Collecting nbstripout
  Downloading nbstripout-0.9.1-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from nbstripout) (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->nbstripout) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->nbstripout) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->nbstripout) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->nbstripout) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->nbstripout) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->nbstripout) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->nbstripout) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->nbstripout) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->nbstripout) (4.9.2)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->nbstripout) (4.15.0)
Downloading nbstripout-0.9.1-py3-none-any.whl (19 kB)
Installing collected packages: nbstripout
Successfully installed nbstripout-0.9.1